version: 3.0.{build}
skip_tags: true
skip_branch_with_pr: true
test: off
pull_requests:
  do_not_increment_build_number: true

os: Visual Studio 2017

environment:
  CI: true

nuget:
  disable_publish_on_pr: true

branches:
  only:
    - master

install:
  - ps: Install-Product node LTS
  - ps: choco install dotnetcore-sdk --no-progress --confirm --version 2.2.104
  - node --version
  - npm --version
  - dotnet --version
  - yarn

build_script:
  - cmd: yarn build-ci

artifacts:
- path: 'artifacts\*.nupkg'
  name: NuGet

deploy:
- provider: NuGet
  server: https://www.myget.org/F/graphql-dotnet/api/v2/package
  api_key:
    secure: +l1vfBMajn1WfmXkQ2LdILKxK4fQ5AHSnnU1kf11Bn1xRGUOTCdPhLwHx232piEn
  skip_symbols: true
  on:
    branch:
      - master
      - next
